### ISSUE TITLE
Unknown option(s) for compilemessages command

### ISSUE THREAD

**Issue by uffsalot** [pc-coholic/pretix-cashpayment#10]
Hi,

I try to update my pretix-cashpayment to 2.0, but I get the following error:

```
(venv) pretix@PRTDEB01:~$ pip3 install -U pretix-cashpayment                                                                                                 Collecting pretix-cashpayment
  Using cached https://files.pythonhosted.org/packages/99/27/c2be2e58fbf96cb955067a2141ca5c04e572d80fc19273ab9c13e1c3b065/pretix-cashpayment-2.0.0.tar.gz
Building wheels for collected packages: pretix-cashpayment
  Running setup.py bdist_wheel for pretix-cashpayment ... error
  Complete output from command /var/pretix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.p
y';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-w
heel-xu3voejd --python-tag cp35:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.py", line 43, in <module>
      """,
    File "/var/pretix/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/var/pretix/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.py", line 17, in run
      management.call_command('compilemessages', verbosity=1, interactive=False)
    File "/var/pretix/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 140, in call_command
      ', '.join(sorted(valid_options)),
  TypeError: Unknown option(s) for compilemessages command: interactive. Valid options are: exclude, fuzzy, help, locale, no_color, pythonpath, settings, ski
p_checks, stderr, stdout, traceback, use_fuzzy, verbosity, version.

  ----------------------------------------
  Failed building wheel for pretix-cashpayment
  Running setup.py clean for pretix-cashpayment
Failed to build pretix-cashpayment
Installing collected packages: pretix-cashpayment
  Found existing installation: pretix-cashpayment 1.0.2
    Uninstalling pretix-cashpayment-1.0.2:
      Successfully uninstalled pretix-cashpayment-1.0.2
  Running setup.py install for pretix-cashpayment ... error
    Complete output from command /var/pretix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup
.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/p
ip-record-_3d_drgz/install-record.txt --single-version-externally-managed --compile --install-headers /var/pretix/venv/include/site/python3.5/pretix-cashpaym
ent:
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.py", line 43, in <module>
        """,
      File "/var/pretix/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/var/pretix/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.py", line 17, in run
        management.call_command('compilemessages', verbosity=1, interactive=False)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 140, in call_command
        ', '.join(sorted(valid_options)),
    TypeError: Unknown option(s) for compilemessages command: interactive. Valid options are: exclude, fuzzy, help, locale, no_color, pythonpath, settings, skip_checks, stderr, stdout, traceback, use_fuzzy, verbosity, version.

    ----------------------------------------
  Rolling back uninstall of pretix-cashpayment
Command "/var/pretix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cgdbv7iy/pretix-cashpayment/setup.py';f=getattr(tokenize,
 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_3d_drgz/insta
ll-record.txt --single-version-externally-managed --compile --install-headers /var/pretix/venv/include/site/python3.5/pretix-cashpayment" failed with error c
ode 1 in /tmp/pip-install-cgdbv7iy/pretix-cashpayment/
```

I am hosting on a Debian 9 LXC Container, no docker involved.
Do you need any other informations to track this issue down?

**Comment by pc-coholic** [comment]
This is probably fixed by PR #9.

I'll try to get around to merge it later today and upload a new package to pypi.

Sorry for the inconvenience caused.

**Comment by uffsalot** [comment]
Thanks for the quick response! I will try it tomorrow ;)

**Comment by pc-coholic** [comment]
I just pushed 2.0.1 to pypi - please give it a try and feel free to reopen this issue if the problem persists.

**Comment by uffsalot** [comment]
Works like a charm, thank you!
